flask re project/flask_app/models.py
from typing import AsyncGenerator

from flask.globals import request
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer, String, ForeignKey
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

class Medicine(db.Model):
    __tablename__ = 'medicine'

    id = db.Column(db.Integer, primary_key=True)
    entpname = db.Column(db.String(22)) 
    itemname = db.Column(db.String(151))
    itemseq = db.Column(db.String(1000))
    efcyqesitm = db.Column(db.String(1000))
    usemethodqesitm = db.Column(db.String(1000))
    atpnwarnqesitm = db.Column(db.String(1000))
    atpnqesitm = db.Column(db.String(2000))
    intrcqesitm = db.Column(db.String(1000))
    seqesitm = db.Column(db.String(981))
    depositmethodqesitm = db.Column(db.String(157))
    opende = db.Column(db.Date)
    updatede = db.Column(db.Date)
    itemimage = db.Column(db.String(70))

    user_medicines = db.relationship("User_medicine", backref="medicine", cascade = 'all, delete')


class Users(db.Model):
    __tablename__ = 'users'

    email = db.Column(db.String(32), db.Sequence('email_seq'), primary_key = True)
    password = db.Column(db.String(32))
    username = db.Column(db.String(32))
    age = db.Column(db.Integer)


class User_medicine(db.Model):
    __tablename__ = 'user_medicine'

    user_target_id = db.Column(db.Integer, primary_key = True)
    medicine_id = db.Column(db.Integer, db.ForeignKey('medicine.id'))
    user_itemname = db.Column(db.String(151))
    user_efcyqesitm = db.Column(db.String(1000))
    user_usemethodqesitm = db.Column(db.String(1000))


  
def get_medicinelist(search=None, check_query=None):
    if search is not None:
        search = f"%{search}%"
        if check_query == 1:
            return Medicine.query.filter(Medicine.entpname.like(search)).all()
        elif check_query == 2:
            return Medicine.query.filter(Medicine.itemname.like(search)).all()
        elif check_query == 3:
            return Medicine.query.filter(Medicine.efcyqesitm.like(search)).all()

    # return Medicine.query.all()


def get_um():
    
    return User_medicine.query.all()


def zero_to_none(data):
    if (data is None) or len(data) == 0:
        return None
    else:
        return data



flask re project/flask_app/__init__.py
from flask import Flask, render_template
from flask_app.models import db, migrate

def create_app():
    app = Flask(__name__) 
    ##db info setting 
    app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql://qhilcsts:1POKik9TwGsb7ObtAflarchaFlRYWIXB@rosie.db.elephantsql.com:5432/qhilcsts" 
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True #사용자에게 정보 전달완료하면 teadown. 그 때마다 커밋=DB반영
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False #추가 메모리를 사용하므로 꺼둔다
    app.secret_key = "secret_key"

    db.init_app(app)
    migrate.init_app(app, db) 

    from flask_app.routes import main_route
    app.register_blueprint(main_route.bp)

    return app

if __name__  == "__main__":
    app = create_app()
    app.run(debug=True)

flask re project/flask_app/routes/main_route.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_app.models import Users, db, Medicine, User_medicine, get_medicinelist, zero_to_none, get_um


bp = Blueprint('main', __name__)

@bp.route("/")
def home():
  return render_template('home.html')


@bp.route("/signup", methods=['GET','POST'])
def signup():
  if request.method == 'POST':
    new_user = Users(
        email=request.form['email'],
        password=request.form['password'],
        username=request.form['username'],
        age=request.form['age'])
    db.session.add(new_user)
    db.session.commit()
    return redirect(url_for('main.login'), code=200)
  return render_template('signup.html')


@bp.route("/login", methods=['GET', 'POST'])
def login():
  if request.method == 'POST':
    email = request.form['email']
    password = request.form['password']
    data = Users.query.filter_by(email=email, password=password).first()
    if data is not None:
      session['email'] = email
      return redirect(url_for('main.home'), code=200)
    else:
      return "[ERROR!] 'email' 또는 'password'가 일치하지 않습니다"
  return render_template('login.html')


@bp.route("/logout", methods=['GET'])
def logout():
  session.pop('email', None)
  return redirect('/')
     

@bp.route('/medicine', methods=['GET', 'POST'])
def medicine_index():
    title = "의약품"
    sub_title = "어떤 의약품들이 있는지 확인해보세요"
    if request.method == 'POST':
        search = zero_to_none(request.form.get('search'))
        check_query = request.form.get('check_query', type=int)
        try:
            medicine_list = get_medicinelist(check_query=check_query, search=search)
        except:
            medicine_list = get_medicinelist()
    else:
        medicine_list = get_medicinelist()
    return render_template('medicine.html', medicine_list=medicine_list, title=title, sub_title=sub_title)


@bp.route('/user', methods=["GET", "POST"])
def user_medicine_index():
  title = '의약품 관리'
  sub_title = '의약품 관리에 오신 것을 환영합니다!'
  
  if request.method == 'POST':
    new_user_medicine = User_medicine(
        medicine_id=request.form['medicine_id'],
        user_itemname=request.form['user_itemname'],
        user_efcyqesitm=request.form['user_efcyqesitm'],
        user_usemethodqesitm=request.form['user_usemethodqesitm'])
    db.session.add(new_user_medicine)
    db.session.commit()
    
  else:
    user_medicine_list=get_um()

  return render_template('user.html', user_medicine_list=user_medicine_list, title=title, sub_title=sub_title)



@bp.route("/delete/<int:user_target_id>")
def delete(user_target_id):
    s = User_medicine.query.get(user_target_id)
    db.session.delete(s)
    db.session.commit()
    return redirect(url_for("main.user_medicine_index"))

flask re project/flask_app/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Medicine Management</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Medicine Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/medicine">Medicine</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/user">User</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/login">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../static/img/의약품.jpeg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {% if title %}
                            <div class="site-heading">
                                <h1>{{ title }}</h1>
                                <span class="subheading">{{ sub_title }}</span>
                            </div>
                        {% else %}
                            <div class="site-heading">
                                <h1>의약품 관리</h1>
                                <span class="subheading">내가 복용하는 의약품을 관리해봅시다</span>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        {% block content %}{% endblock content %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">Copyright 2021 &copy; MEDICINE MANAGEMENT</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src=" {{ url_for('static', filename='scripts.js') }}"></script>
    </body>
</html>

flask re project/flask_app/templates/home.html
{% extends 'base.html' %}

flask re project/flask_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{{ url_for('static', filename='login.css') }}" rel="stylesheet">
    <title>login</title>
  </head>
  <body>
    <div class="loginContainer">
      <div class="loginBox">
        <h1>로그인 페이지입니다.</h1>
        <form method="POST" action="/login">
          <div class="formItem">
            <input placeholder="이메일" name="email" required />
          </div>
          <div class="formItem">
            <input type="password" placeholder="비밀번호" name="password" required />
          </div>
          <div class="buttonWrapper">
            <button type="submit">로그인</button>
          </div>
          <div class="buttonWrapper">
            <button class="signupBtn" onclick="location.href='/signup' ">회원가입</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

flask re project/flask_app/templates/medicine.html
{% extends 'base.html' %}
    {% block content %}
        <!-- Main Content-->
        <form method="post" action="/medicine">
          <center>
          <h2>찾고 싶은 의약품을 검색해보세요!</h2>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="check_query" id="inlineRadio1" value="1" checked>
            <label class="form-check-label" for="inlineRadio1">회사명</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="check_query" id="inlineRadio2" value="2">
          <label class="form-check-label" for="inlineRadio2">제품명</label>
      </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="check_query" id="inlineRadio2" value="3">
          <label class="form-check-label" for="inlineRadio2">효능</label>
      </div>
          <input name="search" style="margin-bottom:10px" class="form-control" type="text" placeholder="검색">
          <input type="submit" class="btn btn-primary" value="찾기"/>
          </center>
        </form>
        <main class="mb-4">
          {% if medicine_list %}
          <table class="table">
            <thead>
              <tr>
                <th scope="col">회사명</th>
                <th scope="col">제품명</th>
                <th scope="col">효능</th>
                <th scope="col">사용법</th>                
              </tr>
            </thead>
            <tbody>
              {% for medicine in medicine_list %}
              <tr>
                  <td>{{ medicine.entpname }}</td>
                  <td>{{ medicine.itemname }}</td>
                  <td>{{ medicine.efcyqesitm }}</td>
                  <td>{{ medicine.usemethodqesitm }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% endif %}   
        </main>
    {% endblock content %}

flask re project/flask_app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{{ url_for('static', filename='signup.css') }}" rel="stylesheet">
    <title>signup</title>
  </head>
  <body>
    <div class="signupContainer">
      <div class="signupBox">
        <header>계정을 생성하세요</header>
        <form method="POST" action="/signup">
          <div class="formItem">
            <label htmlFor="email">이메일</label>
            <input id="email" name="email" required />
          </div>
          <div class="formItem">
            <label htmlFor="password">비밀번호</label>
            <input id="password" name="password" type="password" required />
          </div>
          <div class="formItem">
            <label htmlFor="name">이름</label>
            <input id="name" name="username" required />
          </div>
          <div class="formItem">
            <label htmlFor="age">나이</label>
            <input id="age" name="age" required />
          </div>
          <div class="buttonWrapper">
            <button type="submit" type="primary" shape="round">가입하기</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

flask re project/flask_app/templates/user.html
{% extends 'base.html' %}
    {% block content %}
    <div class="signupContainer">
        <div class="signupBox">
          <form method="POST" action="/user">
            <div class="formItem">
                <label htmlFor="medicine_id">번호</label>
                <input id="medicine_id" name="medicine_id" required />
            </div>
            <div class="formItem">
              <label htmlFor="user_itemname">제품명</label>
              <input id="user_itemname" name="user_itemname" required />
            </div>
            <div class="formItem">
              <label htmlFor="user_efcyqesitm">효능</label>
              <input id="user_efcyqesitm" name="user_efcyqesitm" type="user_efcyqesitm" required />
            </div>
            <div class="formItem">
              <label htmlFor="user_usemethodqesitm">사용법</label>
              <input id="user_usemethodqesitm" name="user_usemethodqesitm" required />
            </div>
            <div class="buttonWrapper">
              <button type="submit" type="primary" shape="round">추가하기</button>
            </div>
          </form>
        </div>
      </div>
        <!-- Main Content-->
        <main class="mb-4">
            {% if user_medicine_list %}
            <table class="table11">
              <thead>
                <tr>
                  <th scope="col">번호</th>
                  <th scope="col">제품명</th>
                  <th scope="col">효능</th>
                  <th scope="col">사용법</th>
                </tr>
              </thead>
              <tbody>
                {% for medicine in user_medicine_list %}
                <tr>
                    <td>{{ medicine.medicine_id }}</td>
                    <td>{{ medicine.user_itemname }}</td>
                    <td>{{ medicine.user_efcyqesitm }}</td>
                    <td>{{ medicine.user_usemethodqesitm }}</td>
                    <td>
                        <a href="{{url_for('main.delete', user_target_id=medicine.user_target_id)}}" class="btn btn-sm btn-danger">삭제</a>
                    </td>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% endif %}   
        </main>
    {% endblock content %}
         